---
name: build

on:
  push:
    branches: [main, "REL-*"]
  workflow_dispatch:

jobs:
  build:   
    steps:
      - name: Cancel previous Action
        uses: styfle/cancel-workflow-action@0.11.0
        continue-on-error: true # for act
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.9.0
        with:
          distribution: 'temurin'
          java-version: 11
          cache: maven         
      - name: Build  with Maven
        run:  mvn -ntp  install
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.2.0
        with:
          junit_files: "**/target/surefire-reports/*.xml"                  



